# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '\u043f\u043e\u0441\u0442', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u044b'),
        ),
    ]
