# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_auto_20170515_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, help_text='<b>\u041c\u0430\u043a\u0441\u0438\u043c\u0443\u043c 300 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432. \u041d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u0432\u044b\u0432\u043e\u0434\u0438\u0442\u0441\u044f \u0442\u043e\u043b\u044c\u043a\u043e 128 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432</b>', max_length=300, null=True, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0438'),
        ),
    ]
