# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041b\u043e\u0433\u0438\u043d'),
        ),
    ]
