# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-06 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20170505_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u043e\u043a\u0435\u043d'),
        ),
    ]
