# coding=utf-8
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(
        r'^logout$',
        users_logout,
        name='users_logout'
    ),
    url(
        r'^login$',
        users_login,
        name='users_login'
    ),
    url(
        r'^register$',
        users_register,
        name='users_register'
    ),
    url(
        r'^email/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/(?P<password>[0-9A-Za-z_\-]+)$',
        users_email_confirm,
        name='users_confirm'
    ),
    url(
        r'^email/confirm/result/(?P<success>[-\w]+)$',
        users_email_confirm_result,
        name='users_confirm_result'
    ),
    url(
        r'^password/set$',
        set_user_password,
        name='users_set_password'
    ),
    url(
        r'^vk/login/callback$',
        vk_auth_response,
        name='vk_login_response'
    ),
    url(
        r'^vk/login$',
        vk_auth,
        name='vk_auth'
    ),
    url(
        r'^ok/login$',
        ok_auth,
        name='ok_auth'
    ),
    url(
        r'^ok/login/callback$',
        ok_auth_response,
        name='ok_auth_response'
    ),
    url(
        r'^facebook/login$',
        fb_auth,
        name='fb_auth'
    ),
    url(
        r'^facebook/login/callback$',
        fb_auth_response,
        name='fb_auth_response'
    ),
    url(
        r'^(?P<user_id>[0-9]+)$',
        profile,
        name='user_profile'
    ),
    url(
        r'^change/password$',
        change_password,
        name='change_password'
    )
]
