# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(help_text='<b style="color: #a2a6ab;">\u0412\u044b \u043c\u043e\u0436\u0435\u0442\u0435 \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u0441\u0440\u0430\u0437\u0443 \u0434\u043e\u0447\u0435\u0440\u043d\u044e\u044e \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e</b>', on_delete=django.db.models.deletion.CASCADE, to='categories.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_app.Coordinates', verbose_name='\u041c\u0435\u0442\u043a\u0430 \u043d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
        migrations.AddField(
            model_name='ad',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0443\u0435\u0442\u0441\u044f \u043c\u0438\u043d\u0438\u043c\u0443\u043c 2 \u0448\u0442.', to='ad_app.Media', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
