# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_app.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
