# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='', verbose_name='\u041c\u0435\u0434\u0438\u0430 \u0444\u0430\u0439\u043b')),
                ('description', models.CharField(blank=True, help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', max_length=255, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0434\u0438\u0430',
                'verbose_name_plural': '\u041c\u0435\u0434\u0438\u0430',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='media',
            field=models.ManyToManyField(blank=True, help_text='\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0443\u0435\u0442\u0441\u044f \u043c\u0438\u043d\u0438\u043c\u0443\u043c 2 \u0448\u0442.', to='ad_app.Media', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0438'),
        ),
    ]
