# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0002_ad_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_active',
        ),
    ]
