# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0003_ad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(help_text='<b style="color: #a2a6ab;">\u0412\u044b \u043c\u043e\u0436\u0435\u0442\u0435 \u0432\u044b\u0431\u0440\u0430\u0442\u044c \u0441\u0440\u0430\u0437\u0443 \u0434\u043e\u0447\u0435\u0440\u043d\u044e\u044e \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e</b>', on_delete=django.db.models.deletion.CASCADE, to='ad_app.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
