# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 15:28
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metro',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
