# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 08:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170510_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u043e \u043d\u0430\u0441', max_length=255)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043e \u043d\u0430\u0441')),
            ],
            options={
                'verbose_name': '\u043e \u043d\u0430\u0441',
                'verbose_name_plural': '\u041e \u043d\u0430\u0441',
            },
        ),
    ]
