# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.City', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='metro',
            name='color',
            field=models.CharField(max_length=10, null=True, verbose_name='\u0426\u0432\u0435\u0442'),
        ),
    ]
