# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170515_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metro',
            name='location',
        ),
    ]
