# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 10:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_metro_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='base_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u043d\u0438\u0437\u0443 \u043a\u0430\u0436\u0434\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
