# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aboutus_base_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='advertisement',
            field=models.FileField(blank=True, help_text='\u0421\u044e\u0434\u0430 PDF\u043d\u0438\u043a \u0440\u0435\u043a\u043b\u0430\u043c\u044b \u043d\u0430 \u0432\u0430\u0448\u0435\u043c \u0441\u0430\u0439\u0442\u0435 \u044f \u043f\u043e\u043b\u043e\u0433\u0430...', null=True, upload_to=b'', verbose_name='\u0420\u0435\u043a\u043b\u0430\u043c\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
    ]
