# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horizontalbanners',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439'),
        ),
        migrations.AddField(
            model_name='verticalbanners',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='horizontalbanners',
            name='life_time',
            field=models.DateField(null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='verticalbanners',
            name='life_time',
            field=models.DateField(null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f'),
        ),
    ]
