# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners_app', '0002_auto_20170515_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannersPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_large_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_large_banner', to='banners_app.VerticalBanners', verbose_name='\u041b\u0435\u0432\u044b\u0439 \u0431\u043e\u043b\u044c\u0448\u043e\u0439 \u0431\u0430\u043d\u043d\u0435\u0440')),
                ('left_small_banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_small_banner', to='banners_app.VerticalBanners', verbose_name='\u041b\u0435\u0432\u044b\u0439 \u043c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0439 \u0431\u0430\u043d\u043d\u0435\u0440')),
                ('middle_banner', models.ForeignKey(blank=True, help_text='\u042d\u0442\u043e\u0442 \u0431\u0430\u043d\u043d\u0435\u0440 \u043f\u043e\u044f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u0437\u0430\u0447\u0430\u0441\u0442\u0443\u044e \u043f\u043e \u0441\u0435\u0440\u0435\u0434\u0438\u043d\u0435 \u0441\u0430\u0439\u0442\u0430', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='middle_banner', to='banners_app.HorizontalBanners', verbose_name='\u0411\u0430\u043d\u043d\u0435\u0440 \u0432 \u0442\u0435\u043b\u0435 \u0441\u0430\u0439\u0442\u0430')),
                ('top_banner', models.ForeignKey(blank=True, help_text='\u0411\u0430\u043d\u043d\u0435\u0440 \u0434\u043e \u0448\u0430\u043f\u043a\u0438', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_banner', to='banners_app.HorizontalBanners', verbose_name='\u0412\u0435\u0440\u0445\u043d\u0438\u0439 \u0431\u0430\u043d\u043d\u0435\u0440')),
            ],
            options={
                'verbose_name': '\u041c\u0435\u0441\u0442\u0430 \u0434\u043b\u044f \u0431\u0430\u043d\u043d\u0435\u0440\u043e\u0432',
                'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430 \u0434\u043b\u044f \u0431\u0430\u043d\u043d\u0435\u0440\u043e\u0432',
            },
        ),
    ]
